"""Tests for the artifact-agnostic Publisher (S3 mocked, git stubbed)."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from unittest.mock import MagicMock

import boto3
import pytest
from moto import mock_aws

from scholar_lens.configs import Github
from scholar_lens.src.aws_helpers import S3Handler
from scholar_lens.src.publisher import (
    Publisher,
    PublishRequest,
    build_pr_body,
    slugify,
)


class TestRedactToken:
    def test_scrubs_token_from_plain_exception(self) -> None:
        err = RuntimeError("clone failed for https://oauth2:ghp_secret@github.com/x")
        redacted = Publisher._redact_token(err, "ghp_secret")
        assert "ghp_secret" not in str(redacted)
        assert "***" in str(redacted)

    def test_structured_exception_does_not_crash_redaction(self) -> None:
        # GitPython's GitCommandError takes structured args; the old
        # type(error)(scrubbed) reconstruction raised TypeError here.
        from git import GitCommandError

        err = GitCommandError(
            ["git", "clone", "https://oauth2:ghp_secret@github.com/x"], 128
        )
        redacted = Publisher._redact_token(err, "ghp_secret")
        assert isinstance(redacted, RuntimeError)
        assert "ghp_secret" not in str(redacted)
        assert "GitCommandError" in str(redacted)  # original type preserved in text

    def test_no_token_returns_original(self) -> None:
        err = ValueError("boom")
        assert Publisher._redact_token(err, None) is err


class TestBuildPrBody:
    def test_renders_header_fields_footer(self) -> None:
        body = build_pr_body(
            kind="paper summary",
            title="Some Paper",
            fields={"Paper ID": "2501.13956", "Characters": "7,000"},
        )
        assert "AI-generated paper summary: **Some Paper**" in body
        assert "- **Paper ID**: 2501.13956" in body
        assert "- **Characters**: 7,000" in body
        assert "automatically generated by the Scholar-Lens system" in body

    def test_empty_fields_are_skipped(self) -> None:
        body = build_pr_body(
            kind="paper review",
            title="T",
            fields={"Paper ID": "x", "Repositories": ""},
        )
        assert "Paper ID" in body
        assert "Repositories" not in body  # empty value omitted


BUCKET = "scholar-lens-test"


class TestSlugify:
    @pytest.mark.parametrize(
        "title,expected",
        [
            ("Getting Started with FastAPI", "getting-started-with-fastapi"),
            ("Foo/Bar: Guide?", "foo-bar-guide"),
            ("///", "untitled"),
        ],
    )
    def test_slugify(self, title: str, expected: str) -> None:
        assert slugify(title) == expected


def _request(work_dir: Path, **overrides) -> PublishRequest:
    base = dict(
        title="My Guide",
        markdown="# Title\n\n![fig](figures/diagram.png)\n",
        work_dir=work_dir,
        branch_id="my-guide",
        pr_title="Tech Guide: My Guide",
        pr_body="body",
        commit_message="feat: add guide",
    )
    base.update(overrides)
    return PublishRequest(**base)  # type: ignore[arg-type]


class TestPublishLocal:
    async def test_publish_without_s3_writes_local_file(self, tmp_path: Path) -> None:
        pub = Publisher(Github(), root_dir=tmp_path)
        request = _request(tmp_path, rewrite_local_images=False)
        s3_url, md_path = await pub.publish(request)
        assert s3_url is None
        assert md_path.exists()
        assert md_path.read_text(encoding="utf-8").startswith("# Title")

    async def test_local_images_rewritten_to_assets_path(self, tmp_path: Path) -> None:
        pub = Publisher(Github(), root_dir=tmp_path)
        request = _request(tmp_path, rewrite_local_images=True)
        _, md_path = await pub.publish(request)
        content = md_path.read_text(encoding="utf-8")
        # Local "figures/diagram.png" becomes "/assets/<file>/diagram.png".
        assert "/assets/" in content and "diagram.png" in content
        assert "figures/diagram.png" not in content

    async def test_publish_applies_markdown_lint(self, tmp_path: Path) -> None:
        # publish() runs the lint pass for EVERY artifact (review/summary/guide
        # all go through this same method): a heading glued to the previous line
        # gets its blank line (the one auto-fix).
        pub = Publisher(Github(), root_dir=tmp_path)
        request = _request(
            tmp_path,
            markdown="intro line\n## Section\nbody\n",
            rewrite_local_images=False,
        )
        _, md_path = await pub.publish(request)
        content = md_path.read_text(encoding="utf-8")
        assert "intro line\n\n## Section" in content  # blank line inserted

    async def test_http_images_untouched(self, tmp_path: Path) -> None:
        pub = Publisher(Github(), root_dir=tmp_path)
        request = _request(
            tmp_path,
            markdown="![x](https://cdn.example.com/a.png)",
            rewrite_local_images=True,
        )
        _, md_path = await pub.publish(request)
        assert "https://cdn.example.com/a.png" in md_path.read_text(encoding="utf-8")

    async def test_absolute_local_scratch_path_rewritten(self, tmp_path: Path) -> None:
        # Figure enrichment injects an ABSOLUTE local path as the image src for
        # PDF-parsed papers (e.g. /Users/.../figures/0.png). It must be rewritten
        # to this post's asset dir, not shipped verbatim (which 404s on the blog).
        pub = Publisher(Github(), root_dir=tmp_path)
        request = _request(
            tmp_path,
            markdown="# T\n\n![fig](/Users/me/papers/x/figures/0.png)\n",
            rewrite_local_images=True,
        )
        _, md_path = await pub.publish(request)
        content = md_path.read_text(encoding="utf-8")
        assert "/Users/me/papers/x/figures/0.png" not in content
        assert "/assets/" in content and "/0.png)" in content

    async def test_remote_image_url_with_parens_not_truncated(
        self, tmp_path: Path
    ) -> None:
        # A URL containing parens (Wikipedia/arXiv style) must not be truncated at
        # the first ')': the tail would leak as prose and the image would break.
        url = "https://upload.wikimedia.org/File_(diagram).png"
        pub = Publisher(Github(), root_dir=tmp_path)
        request = _request(
            tmp_path,
            markdown=f"# T\n\n![arch]({url})\n",
            rewrite_local_images=True,
        )
        _, md_path = await pub.publish(request)
        content = md_path.read_text(encoding="utf-8")
        assert f"![arch]({url})" in content  # intact, remote → untouched

    async def test_local_image_path_with_parens_rewritten_whole(
        self, tmp_path: Path
    ) -> None:
        # A local path with parens must be rewritten using its FULL basename, not
        # a truncated one (which would 404 on the blog).
        pub = Publisher(Github(), root_dir=tmp_path)
        request = _request(
            tmp_path,
            markdown="# T\n\n![x](/tmp/figures/fig_(a).png)\n",
            rewrite_local_images=True,
        )
        _, md_path = await pub.publish(request)
        content = md_path.read_text(encoding="utf-8")
        assert "/tmp/figures/fig_(a).png" not in content
        assert "fig_(a).png)" in content  # full basename preserved in the rewrite

    async def test_already_hosted_asset_path_untouched(self, tmp_path: Path) -> None:
        # A path already under THIS post's asset dir must be left as-is (idempotent
        # re-publish), not double-prefixed.
        file_name = f"{datetime.now().strftime('%Y-%m-%d')}-my-guide"
        hosted = f"/assets/{file_name}/0.png"
        pub = Publisher(Github(), root_dir=tmp_path)
        request = _request(
            tmp_path,
            markdown=f"# T\n\n![fig]({hosted})\n",
            rewrite_local_images=True,
        )
        _, md_path = await pub.publish(request)
        content = md_path.read_text(encoding="utf-8")
        assert content.count(hosted) == 1
        assert f"/assets/{file_name}/{file_name}" not in content  # no double-prefix


class TestPublishS3:
    async def test_publish_uploads_post_and_returns_s3_url(
        self, tmp_path: Path
    ) -> None:
        with mock_aws():
            client = boto3.client("s3", region_name="us-east-1")
            client.create_bucket(Bucket=BUCKET)
            handler = S3Handler(boto3.Session(region_name="us-east-1"), BUCKET)

            pub = Publisher(
                Github(),
                root_dir=tmp_path,
                s3_handler=handler,
                s3_bucket_name=BUCKET,
                s3_prefix="scholar-lens",
            )
            request = _request(tmp_path, rewrite_local_images=False)
            s3_url, _ = await pub.publish(request)
            assert s3_url is not None
            assert s3_url.startswith(f"s3://{BUCKET}/scholar-lens/posts/")
            # The post object exists in the bucket.
            keys = [
                o["Key"]
                for o in client.list_objects_v2(Bucket=BUCKET).get("Contents", [])
            ]
            assert any(k.endswith(".md") for k in keys)


class TestCreatePullRequest:
    async def test_skips_when_repo_not_configured(self, tmp_path: Path) -> None:
        pub = Publisher(Github(repo_name=None), root_dir=tmp_path)
        request = _request(tmp_path)
        # Should return without raising (no repo configured).
        await pub.create_pull_request(request, tmp_path / "x.md")

    async def test_skips_when_token_missing(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.delenv("GITHUB_TOKEN", raising=False)
        pub = Publisher(Github(repo_name="owner/blog"), root_dir=tmp_path)
        request = _request(tmp_path)
        await pub.create_pull_request(request, tmp_path / "x.md")  # no raise


class TestGitOperations:
    """Exercise the real git flow against a LOCAL bare repo (no network).

    Verifies the committer identity is set (regression: the Batch container has
    no global git identity, so a commit failed with "empty ident name"), and
    that extracted figures are copied into the blog's assets/<post>/ dir.
    """

    def _make_bare_remote(self, tmp_path: Path) -> Path:
        from git import Repo

        # A bare repo with an initial commit on `main` to branch from.
        seed = tmp_path / "seed"
        seed.mkdir()
        seed_repo = Repo.init(seed, initial_branch="main")
        with seed_repo.config_writer() as cfg:
            cfg.set_value("user", "name", "seed")
            cfg.set_value("user", "email", "seed@example.com")
        (seed / "README.md").write_text("seed", encoding="utf-8")
        seed_repo.git.add(all=True)
        seed_repo.git.commit("-m", "init")
        bare = tmp_path / "remote.git"
        seed_repo.clone(bare, bare=True)
        return bare

    async def test_commit_succeeds_and_copies_figures(self, tmp_path: Path) -> None:
        bare = self._make_bare_remote(tmp_path)

        # A post with a figure that must travel into assets/<post>/.
        work_dir = tmp_path / "work"
        figures = work_dir / "figures"
        figures.mkdir(parents=True)
        (figures / "diagram.png").write_bytes(b"PNG")
        markdown_path = work_dir / "2026-06-07-my-post.md"
        markdown_path.write_text(
            "# T\n\n![fig](/assets/2026-06-07-my-post/diagram.png)\n",
            encoding="utf-8",
        )

        pub = Publisher(
            Github(
                repo_name="owner/blog",
                base_branch="main",
                author_name="Bot",
                author_email="bot@example.com",
            ),
            root_dir=tmp_path,
        )
        clone_dir = tmp_path / "clone"
        # Point the clone at the local bare repo instead of github.com.
        pub._git_operations_inner(
            clone_dir,
            branch_name="paper-reviews/my-post",
            commit_message="feat: add my post",
            markdown_path=markdown_path,
            repo_url=str(bare),
        )

        from git import Repo

        repo = Repo(clone_dir)
        # The commit landed (committer identity was set) with our author.
        head = repo.head.commit
        assert head.author.name == "Bot"
        assert head.committer.email  # non-empty committer identity
        # The figure was copied into the blog's assets/<post>/ layout.
        copied = clone_dir / "assets" / markdown_path.stem / "diagram.png"
        assert copied.exists()
        # The post markdown is in _posts/.
        assert (clone_dir / "_posts" / markdown_path.name).exists()

    async def test_git_and_pr_invoked_when_configured(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        pub = Publisher(Github(repo_name="owner/blog"), root_dir=tmp_path)

        git_calls = MagicMock()
        monkeypatch.setattr(pub, "_git_operations", git_calls)

        created = {}

        class FakeRepo:
            def create_pull(self, **kwargs):  # type: ignore[no-untyped-def]
                created.update(kwargs)

        class FakeGithub:
            def __init__(self, *a, **k) -> None:
                pass

            def get_repo(self, name):  # type: ignore[no-untyped-def]
                return FakeRepo()

        monkeypatch.setattr("scholar_lens.src.publisher.Github", FakeGithub)
        request = _request(tmp_path)
        await pub.create_pull_request(request, tmp_path / "x.md")

        git_calls.assert_called_once()
        assert created["title"] == "Tech Guide: My Guide"
        assert created["base"] == "main"
