"""Artifact-agnostic publishing: save markdown, upload to S3, open a blog PR.

Reviews, summaries and technical guides all produce a Markdown document plus an
optional directory of figures. This module centralises the "ship it" steps so
every artifact type publishes identically:

* write the Markdown to a local file (rewriting local image paths to the blog's
  assets layout),
* upload the post + figures to S3, and
* open a pull request against the configured github.io blog repository.
"""

from __future__ import annotations

import asyncio
import os
import re
import shutil
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from git import Repo
from github import Auth, Github, GithubException

from .aws_helpers import S3Handler
from .constants import EnvVars, LocalPaths, S3Paths
from .logger import logger
from .markdown_lint import lint_markdown
from .markdown_math import normalize_math_underscores

if TYPE_CHECKING:
    from ..configs import Github as GithubConfig

_IMAGE_EXTENSIONS = [".gif", ".jpg", ".jpeg", ".png", ".svg", ".webp"]
# Image target tolerates one level of parens in the URL/path (e.g. Wikipedia's
# ``File_(diagram).png`` or a scratch path ``fig_(a).png``). A naive ``(.*?)``
# stops at the first ``)``, truncating the URL — the tail leaks as prose and the
# rewritten local path 404s. The balanced group ``[^()]*(\([^()]*\)[^()]*)*``
# still stops at the real closing paren, so multiple images per line split fine.
_MARKDOWN_IMAGE_PATTERN = r"!\[(.*?)\]\(([^()]*(?:\([^()]*\)[^()]*)*)\)"


@dataclass
class PublishRequest:
    """Everything needed to publish one artifact."""

    title: str
    markdown: str
    work_dir: Path
    branch_id: str
    pr_title: str
    pr_body: str
    commit_message: str
    rewrite_local_images: bool = True
    figures_dirname: str = LocalPaths.FIGURES_DIR.value
    extra_metadata: dict[str, str] = field(default_factory=dict)


def slugify(title: str, max_length: int = 120) -> str:
    """Filesystem- and S3-safe slug for a document title."""
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:max_length].strip("-")
    return slug or "untitled"


# Footer shared by every auto-generated blog PR body.
_PR_FOOTER = "This pull request was automatically generated by the Scholar-Lens system."


def build_pr_body(*, kind: str, title: str, fields: dict[str, str]) -> str:
    """Build a consistent blog-PR description across all artifact types.

    ``kind`` is the human label ("paper review" / "paper summary" / "technical
    guide"); ``fields`` are the artifact-specific metadata rows (rendered as
    ``- **Key**: value``), in insertion order. Empty-valued fields are skipped so
    each artifact only shows what's relevant, while the header/footer stay
    identical."""
    header = f"This PR adds an AI-generated {kind}: **{title}**"
    rows = "\n".join(f"- **{k}**: {v}" for k, v in fields.items() if v)
    return f"{header}\n\n{rows}\n\n{_PR_FOOTER}"


class Publisher:
    """Publishes artifacts to S3 and the configured blog repository."""

    def __init__(
        self,
        github_config: GithubConfig,
        *,
        root_dir: Path,
        s3_handler: S3Handler | None = None,
        s3_bucket_name: str | None = None,
        s3_prefix: str = "",
    ) -> None:
        self.github_config = github_config
        self.root_dir = root_dir
        self.s3_handler = s3_handler
        self.s3_bucket_name = s3_bucket_name
        self.s3_prefix = s3_prefix

    async def publish(self, request: PublishRequest) -> tuple[str | None, Path]:
        """Save + upload the artifact; return (s3_url, local_markdown_path)."""
        # The post filename is prefixed with the publish date (today); the paper's
        # own date lives in the front-matter `date` field, set by the caller.
        file_name = f"{datetime.now().strftime('%Y-%m-%d')}-{slugify(request.title)}"
        markdown = request.markdown
        # Escape underscores inside math so kramdown(GFM) doesn't eat subscripts
        # before MathJax renders (a recurring blog-rendering issue).
        markdown = normalize_math_underscores(markdown)
        # Auto-fix other kramdown/MathJax pitfalls (blank line before headings,
        # bare | in math) and warn about risky ones (single-$ math, undefined
        # macros, non-URL links).
        markdown = lint_markdown(markdown)
        if request.rewrite_local_images:
            markdown = self._rewrite_local_images(markdown, file_name)

        markdown_path = request.work_dir / f"{file_name}.md"
        await asyncio.to_thread(markdown_path.write_text, markdown, encoding="utf-8")

        s3_url = await self._upload_to_s3(request, file_name, markdown_path)
        return s3_url, markdown_path

    def _rewrite_local_images(self, markdown: str, file_name: str) -> str:
        assets_path = f"/{S3Paths.ASSETS.value}/{file_name}"

        def repl(match: re.Match) -> str:
            alt_text, img = match.group(1), match.group(2)
            # Remote images stay as-is.
            if img.startswith(("http://", "https://")):
                return match.group(0)
            # Already pointing at this post's asset dir — leave it.
            if img.startswith(f"{assets_path}/"):
                return match.group(0)
            # Everything else — a relative name, or an ABSOLUTE local scratch path
            # like "/Users/.../figures/0.png" injected by figure enrichment — is a
            # figure this post owns. All figures upload flat into `assets_path`, so
            # rewrite to the hosted basename. (Previously any "/"-prefixed path was
            # skipped, so absolute local paths shipped verbatim and 404'd.)
            return f"![{alt_text}]({assets_path}/{Path(img).name})"

        return re.sub(_MARKDOWN_IMAGE_PATTERN, repl, markdown)

    async def _upload_to_s3(
        self, request: PublishRequest, file_name: str, markdown_path: Path
    ) -> str | None:
        if not self.s3_handler:
            return None
        prefix = self.s3_prefix or ""
        posts_key = f"{prefix}/{S3Paths.POSTS.value}".lstrip("/")
        assets_key = f"{prefix}/{S3Paths.ASSETS.value}/{file_name}".lstrip("/")
        await self.s3_handler.upload_file_async(markdown_path, posts_key)

        figures_dir = request.work_dir / request.figures_dirname
        if figures_dir.exists():
            await asyncio.to_thread(
                self.s3_handler.upload_directory,
                figures_dir,
                assets_key,
                file_extensions=_IMAGE_EXTENSIONS,
                public_readable=self.github_config.public_assets,
            )
        return f"s3://{self.s3_bucket_name}/{posts_key}/{file_name}.md"

    async def create_pull_request(
        self, request: PublishRequest, markdown_path: Path
    ) -> str | None:
        """Open a blog PR and return its URL (None if skipped or on failure —
        never raises, so a publish hiccup can't fail the pipeline)."""
        repo_config = self.github_config
        if not repo_config.repo_name:
            logger.error("GitHub repository not configured.")
            return None
        repo_name = repo_config.repo_name  # narrowed to str for the closures below
        token = os.getenv(EnvVars.GITHUB_TOKEN.value)
        if not token:
            logger.error(
                "GitHub token not found in environment variable '%s'.",
                EnvVars.GITHUB_TOKEN.value,
            )
            return None

        clone_dir = self.root_dir / LocalPaths.GITHUB_CLONE_DIR.value
        try:
            timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
            branch_name = f"{repo_config.branch_prefix}/{request.branch_id}-{timestamp}"
            await asyncio.to_thread(
                self._git_operations,
                clone_dir,
                branch_name,
                request.commit_message,
                markdown_path,
            )
            logger.info("Creating a pull request on GitHub...")
            # PyGithub is synchronous (blocking HTTP); run off the event loop so
            # it doesn't stall other coroutines — mirrors the git-ops call above.
            gh_repo = await asyncio.to_thread(
                lambda: Github(auth=Auth.Token(token)).get_repo(repo_name)
            )
            try:
                pull = await asyncio.to_thread(
                    lambda: gh_repo.create_pull(
                        title=request.pr_title,
                        body=request.pr_body,
                        head=branch_name,
                        base=repo_config.base_branch,
                    )
                )
                logger.info("Successfully created a pull request: '%s'", pull.html_url)
                return pull.html_url
            except GithubException as e:
                if e.status == 422 and "A pull request already exists" in str(e.data):
                    logger.warning(
                        "Pull request for branch '%s' already exists.", branch_name
                    )
                    return None
                raise
        except Exception as e:
            logger.error("Failed to create GitHub pull request: %s", e, exc_info=True)
            return None
        finally:
            if clone_dir.exists():
                await asyncio.to_thread(shutil.rmtree, clone_dir, ignore_errors=True)
                logger.info("Cleaned up local clone directory: '%s'", clone_dir)

    def _git_operations(
        self,
        clone_dir: Path,
        branch_name: str,
        commit_message: str,
        markdown_path: Path,
    ) -> None:
        repo_config = self.github_config
        token = os.getenv(EnvVars.GITHUB_TOKEN.value)
        repo_url = f"https://oauth2:{token}@github.com/{repo_config.repo_name}.git"
        try:
            self._git_operations_inner(
                clone_dir, branch_name, commit_message, markdown_path, repo_url
            )
        except Exception as e:
            # GitPython embeds the failing command (including the tokened clone
            # URL) in its exception text; scrub the token before it propagates or
            # gets logged so credentials never leak into logs/SNS/Slack.
            raise self._redact_token(e, token) from None

    @staticmethod
    def _redact_token(error: Exception, token: str | None) -> Exception:
        if not token:
            return error
        scrubbed = str(error).replace(token, "***")
        # Return a plain RuntimeError rather than reconstructing the original
        # class. Exceptions like GitCommandError / GithubException take structured
        # constructor args, so type(error)(scrubbed) would raise TypeError inside
        # redaction and mask the failure. Keep the original class name in the text
        # for debuggability; the token is what must never survive.
        return RuntimeError(f"{type(error).__name__}: {scrubbed}")

    def _git_operations_inner(
        self,
        clone_dir: Path,
        branch_name: str,
        commit_message: str,
        markdown_path: Path,
        repo_url: str,
    ) -> None:
        repo_config = self.github_config
        if clone_dir.exists():
            shutil.rmtree(clone_dir)

        logger.info("Cloning repository '%s' to '%s'", repo_config.repo_name, clone_dir)
        repo = Repo.clone_from(repo_url, clone_dir)

        if branch_name in repo.heads:
            new_branch = repo.heads[branch_name]
        else:
            new_branch = repo.create_head(
                branch_name, repo.remotes.origin.refs[repo_config.base_branch]
            )
        new_branch.checkout()

        posts_dir = clone_dir / LocalPaths.POSTS_DIR.value
        posts_dir.mkdir(exist_ok=True)
        shutil.copy(markdown_path, posts_dir)
        logger.info("Copied markdown file to '%s'", posts_dir)

        figures_dir = markdown_path.parent / LocalPaths.FIGURES_DIR.value
        if figures_dir.exists():
            assets_target_dir = (
                clone_dir / LocalPaths.ASSETS_DIR.value / markdown_path.stem
            )
            assets_target_dir.mkdir(parents=True, exist_ok=True)
            shutil.copytree(figures_dir, assets_target_dir, dirs_exist_ok=True)
            logger.info("Copied figures to '%s'", assets_target_dir)

        if not repo.is_dirty(untracked_files=True):
            logger.warning("No changes to commit. Skipping push and pull request.")
            return

        logger.info("Committing changes...")
        repo.git.add(all=True)
        # Set the committer identity on this repo. ``--author`` only sets the
        # author; git still refuses to commit without a committer name/email,
        # which the Batch container does not have globally ("empty ident name").
        with repo.config_writer() as cfg:
            cfg.set_value("user", "name", repo_config.author_name)
            if repo_config.author_email:
                cfg.set_value("user", "email", repo_config.author_email)
        author_actor = (
            f"{repo_config.author_name} <{repo_config.author_email}>"
            if repo_config.author_email
            else repo_config.author_name
        )
        repo.git.commit("-m", commit_message, f"--author={author_actor}")

        logger.info("Pushing changes to branch '%s'...", branch_name)
        repo.remote(name="origin").push(
            refspec=f"{branch_name}:{branch_name}", force=True
        )
